### ISSUE TITLE
implement node-enocean.js to node red

### ISSUE THREAD

**Issue by Jo-rauh** [enocean-js/node-enocean#28]
Hello everybody,

I am completely new to programming and to Github also.  I just want to implement a node red flow beeing able to decode lots of Enocean EEPs. My hardware is a raspberry Pi and the tcm310 enocean gateway. In fhem i can see that everything is working. My plan is to get the sensor data to ms azure. I think node red would be the best choice for a beginner like me. Now i integrated node-enocean to node red (via global context). But lots of the funktins like enocean.on or enocean.listen do not work in the function node. I know that there exist already Enocean-nodes for node red but the enocean-node.js can handle more EEPs and i want to be flexible in choosing sensors.

I am looking forward to your answers!

Thank you very much.

Johannes

**Comment by Holger-Will** [comment]
i suggest you try to get a basic example working. For that, clone or download the repository, go to the examples folder and try to run the examples. You might have to change the "path" to your usb device.

On Windows its usually something like "COM1", "COM2" etc. whereas on linux/mac it's "/dev/ttyUSB0" etc. all the examples are written to work on standard linux. you have to change the com-port to the one assigned to your device by your system. 

If you get the basic example to run, you are good to go and write the node-red node.
if you have further questions, don't hesitate to ask.
(Ich spreche auch deutsch...)

**Comment by nabbl** [comment]
A **Node-Red** node would be absolutely amazing. Currently there are only the ones from "thethingbox" and to be honest... it is not really working. The way they handle the baseid and generate telegrams is more than dodgy. And all in all the code is kind of unreadable and unmaintainable.

I will try to write one on my own. But that can take a while as I have no time at the moment.

**Comment by Holger-Will** [comment]
i haven't looked into node-red myself, but i'm willing to work on it a bit. we could start a joint project to create a node-red node.

**Comment by Jo-rauh** [comment]
That sounds perfect. How would you like to start? At the moment I configured the serial-port-node in node red with dey/tty/AMA0. When i press the learn button of my enocean sensor i get a Hexcode in the debug window. I think adding a function node configured with the node-enocean code of you would be the easiest solution. It would be amazing if we can create a flow where the Sensor directly outputs the temperature  by pressing the learn button and not a hexcode. Then users are able to use the values in node-red Dashboard, in a cloud service or whatever. What do you think about it?

**Comment by nabbl** [comment]
I am on it right now. pull request should come soon.

I think we need something a bit more powerful.

1. there should be a config node to configure if you use the enoceanHAT oder USB300 stick
2. There needs to be a listener node which listens for incoming telegrams
3. you need to be able to configure if this listener node should only listen for known sensors.
4. you should be able to tell the listener node which device to listen to out of a dropdown list
5. you need to be able to send telegrams. so you will need  several button nodes. new buttons should have a baseid + integer++
6. you need a learn-node to fill the knownSensors.json. these new devices should be named according to what the user wants.

and a lot more stuff I can't think of right now.

**Comment by Holger-Will** [comment]
graet stuff!
renamed the node-red-enocean to node-red-contrib-enocean to follow node-red naming conventions.
the repository can be found here: https://github.com/node-enocean/node-red-contrib-enocean

**Comment by nabbl** [comment]
I know that this is closed. The package is available on NPM:

https://www.npmjs.com/package/node-red-contrib-enocean

**Comment by Niazmorshed19** [comment]
hi, i am working in a project with enocean pi and raspberry. i have to build a GUI in raspberry pi using Enocean switch +Raspberry pi +5 inch LCD display. can anyone help me with some suggestions/ any documents.? I have seen the post but visually have anyone some instructions guide for node red?[https://hackaday.io/project/11830-clouds-happen/log/41602-revised-enocean-pi-for-automation-of-physical-objects](url)

**Comment by Holger-Will** [comment]
no further documentation, yet. 
I'm not much into node-red, but more into the low level enocean stuff. Can you describe your project in more detail?
oh and can you please open a new issue, asking for help on your project, please? so to keep this bug cleaner. thanks!

**Comment by Niazmorshed19** [comment]
Hallo,
I also live in Berlin. My project is to make a GUI by using Pi and Enocean.
I have seen your instructions on GitHub. But I don’t find where I have to
put your code in node red . I request you to send some pictures that you
edited your node red pallets for Enocean switches and sensors.

Thanks

Best wishes
Niaz

**Comment by es101** [comment]
I had running contrib-enocean on a rasperry pi with enocean pi. Every thing worked well with enocean-listener and enocean-switch.
But now, after a reinstallation, I am not able to run the flow.
I get the mwssage: "could not open port. Most likely you are trying to open the same port twice."
and "could not get Base ID".
The input-node tells "Not initialized".
What can I do?

Regards

Erwin

**Comment by nabbl** [comment]
You have to enable the serial port via `sudo raspi-config`
select option 5 -> option P6 -> select NO for logging and Yes for enabling

Also disable UART:
`sudo systemctl disable hciuart`

**Comment by Holger-Will** [comment]
what does it say which version you have installed? you have most likely installed the new version that I currently work on 

https://github.com/enocean-js/enocean-js/issues/62 
https://flows.nodered.org/node/node-red-contrib-enocean

unfortunately, it is not backward compatible with the old one... you most likely have to rewrite your flow(s)... sorry :-(

the documentation for the new node is still lacking and outdated. If you have any question or need some assistance please ask over at the new repository [enocean-js](https://github.com/enocean-js/enocean-js)

**Comment by Holger-Will** [comment]
you can also ask over at the node-red forum... https://discourse.nodered.org/t/announce-node-red-contrib-enocean/10135/12

**Comment by es101** [comment]
Unfortunately this does  not work.
Same situation. Input: not initialized. Serialport: /dev/ttyAMA0.

Am Montag, den 13.05.2019, 03:08 -0700 schrieb Daniel Kappler:

**Comment by nabbl** [comment]
yes be sure to install the old version if you want it to behave like before:

In package.json of node-red:
"node-red-contrib-enocean": "git+https://git@github.com/enocean-js/node-red-contrib-enocean.git"

**Comment by Holger-Will** [comment]
I can only strongly advice against using the old module. there are a few security vulnerabilities in `node-enocean` already, and it does not work with the current node-red. The old node-red version it works with also has some security vulnerabilities... neither node-enocean nor the old version is actively maintained...
