### ISSUE TITLE
Upgrade serialport dependency

### ISSUE THREAD

**Issue by altery** [enocean-js/node-enocean#42]
Any plans on upgrading the serialport dependency (to v6 or v7)? I'm getting a lot of deprecating warnings while compiling the native part of the library.

**Comment by Holger-Will** [comment]
i would love to, currently i use https://github.com/RafaelKa/node-serialport-enocean-parser a specialized serialport parser which is a bit outdated... i see what i can do patching it myself. But you can  leave a bug report there as well... it might help.

**Comment by Holger-Will** [comment]
just created a pull request on https://github.com/RafaelKa/node-serialport-enocean-parser lets see how the response is. otherwise i'll push my version to npm and use that going forward...

**Comment by tim-hellhake** [comment]
Resolved by https://github.com/enocean-js/node-enocean/pull/54

I think you can close this now @Holger-Will
