### ISSUE TITLE
node-enocean does not work with node 10

### ISSUE THREAD

**Issue by altery** [enocean-js/node-enocean#43]
node-enocean pulls in level ^1.6. The 1.x branch of level (actually leveldown) is not compatible with the current LTS of node (10.x). The dependency should be upgraded if possible. Alternatively, the dependency should be optional - level db is only used to remember nodes using teach-in. This functionality is not required to use the library (at least I don't use it :) )

**Comment by Holger-Will** [comment]
thanks for letting me know... i will try to update this weekend.

**Comment by Holger-Will** [comment]
i plan a complete rewrite and use a more modular approach. that way i'll get rid of unnecessary dependencies...

**Comment by Holger-Will** [comment]
If you don't need db functionality, the easiest way (for now) is to use the [Serialport ESP3Parser](https://github.com/RafaelKa/node-serialport-enocean-parser) directly in combination with the [eep-transcoder](https://github.com/node-enocean/eep-transcoder) there is a [working example](https://github.com/RafaelKa/node-serialport-enocean-parser/blob/master/examples/DecodeEEP.js) in the ESP3Parser  respository.

this is all done in an affort to modularize node-enocean, so you can only pull in the stuff you need.

as you can see though, the transcoder is at 0.1.0 and the parser ist at 0.2.0 (soon to be 1.0.0) so expect that things will break ;-)

I will update more often in the coming weeks!

**Comment by Holger-Will** [comment]
oh... the transcoder will eventually pull in https://github.com/node-enocean/eep-spec as a source of truth for all packet information. Help Wanted!
